name: Build snap and run tests

on:
  workflow_call:
    outputs:
      snap-file:
        description: "The snap output of build process."
        value: ${{ jobs.build.outputs.snap-file }}

jobs:
  check:
    name: Check build condition for Snap
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true
      matrix:
        python-version:
          - '3.9'
          - '3.10'
    steps:
      - id: checkout
        name: Checkout repo
        uses: actions/checkout@v3
      - id: setup-python
        name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{matrix.python-version}}
          architecture: x64
      - id: code-checks
        name: Make sure the code follows conventions and tests correctly
        run: |
          make checks
  build:
    name: Build Snap
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs:
      - check
    outputs:
      snap-file: ${{ steps.build-snap.outputs.snap }}
    steps:
      - id: checkout
        name: Checkout repo
        uses: actions/checkout@v3
      - id: build-snap
        name: Build snap
        uses: snapcore/action-build@v1
        with:
          snapcraft-channel: 7.x/candidate
      - id: upload
        name: Upload built snap job artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.build-snap.outputs.snap }}
          path: ${{ steps.build-snap.outputs.snap }}

  test:
    name: Test Snap
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs:
      - check
      - build
    steps:
      - name: Download snap file
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build.outputs.snap-file }}
          path: .

      - name: Install snap file
        run: |
          sudo snap install ${{ needs.build.outputs.snap-file }} --dangerous

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Integration Tests
        run: |
          make integration-tests